### PR TITLE
CB-11412 Update templates to designate template source dir

### PR DESCRIPTION
**Pull request by carynbear**

### CODE REVIEW

**Comment by devgeeks** [comment]
I assume these are in prep for the changes to templates and should not be pulled in yet?

**Comment by stevengill** [comment]
Probably needs a quick review but it should work with existing cordova as well next one with the changes

**Comment by devgeeks** [comment]
OK. I'll review it today then!

**Comment by mwbrooks** [comment]
I left a few comments on phonegap/phonegap-template-framework7#6 that are related to this one.

**Comment by mwbrooks** [comment]
Heads up, I noticed that this was merged. Will it not break the current releases of the PhoneGap / Cordova CLIs? Merging it prevents us from doing any patches until the next Cordova update.

**Comment by stevengill** [comment]
existing cordova-cli template work should work with this updated template.

**Comment by devgeeks** [comment]
I tested it with:

```
~ Brodie 💀  cordova --version
6.2.0
~ Brodie 💀  phonegap --version
6.2.6
```

And it worked fine. It's not published to `npm` quite yet though just in case something comes up with the Desktop app review of `hello-world`

**Comment by stevengill** [comment]
Yeah, i tested it with cordova 6.2.0 and with the new PR [1] by @carynbear enhancing template support. Works with both. 

With the new PR [1], `package.json` name and version field will also be updated. 

@devgeeks if you want, you can modify the default values in the `package.json` inside `template_src`. So the name, version, author, etc can all be dumb default values. Something similar to [2]. Of course, you will probably want to leave in the scripts object and dependencies. 

[1] https://github.com/apache/cordova-lib/pull/456
[2] https://github.com/phonegap/phonegap-template-blank/blob/master/template_src/package.json

**Pull request merged**
